package frame;
import com.sun.glass.events.KeyEvent;
import static frame.JFrameMenu.lbRolMenuPrincipal;
import javax.swing.JOptionPane;
import modelo.DatosUsuarios;
import modelo.ProcesoLoginUsuario;


public class JFrameLogin extends javax.swing.JFrame {
    DatosUsuarios logUsuDatos = new DatosUsuarios();
    ProcesoLoginUsuario procesoLoUsu = new ProcesoLoginUsuario();
    public JFrameLogin() {
        initComponents();
        this.setResizable(false);/*Quitamos la opción de maximizar*/
        this.setLocationRelativeTo(null);/*Centramos la ventana*/
    }
    public void validarInicioSesion(){
        String usuario= txtUsuarioLogin.getText();
        String clave = String.valueOf(txtClaveLogin.getPassword());
        if(!"".equals(usuario) && !"".equals(clave)){
            logUsuDatos=procesoLoUsu.iniciar_sesion(usuario, clave);
            if(logUsuDatos.getLogin_Usuario_usuario() !=null && logUsuDatos.getLogin_Usuario_clave() !=null){
                if("Administrador".equalsIgnoreCase(logUsuDatos.getLogin_Usuario_rol())){
                    if("Activo".equalsIgnoreCase(logUsuDatos.getLogin_Usuario_estado_cuenta())){
                        JOptionPane.showMessageDialog(null, "Bienvenidos señor/a "+logUsuDatos.getLogin_Usuario_nombre(),"Inicio de sesión - Administrador",JOptionPane.INFORMATION_MESSAGE);
                        JFrameMenu menuPrincipal = new JFrameMenu();
                        menuPrincipal.setVisible(true);
                        JFrameMenu.lbRolMenuPrincipal.setText("Administrador");
                        lbRolMenuPrincipal.setVisible(false);
                        JFrameMenu.LbCedulaUsuarioIngresado.setText(logUsuDatos.getLogin_Usuario_cedula()+"");
                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(null, "Su usuario está bloqueado","Inicio de sesión",JOptionPane.WARNING_MESSAGE);
                        txtClaveLogin.setText("");
                        txtUsuarioLogin.setText("");
                        txtUsuarioLogin.requestFocus();
                    }
                }else{
                    if("Activo".equalsIgnoreCase(logUsuDatos.getLogin_Usuario_estado_cuenta())){
                        JOptionPane.showMessageDialog(null, "Bienvenidos señor/a "+logUsuDatos.getLogin_Usuario_nombre(),"Inicio de sesión - Personal médico",JOptionPane.INFORMATION_MESSAGE);
                        JFrameMenu menuPrincipal = new JFrameMenu();
                        menuPrincipal.setVisible(true);
                        JFrameMenu.JMenuRegistrarUsuarios.setVisible(false);
                        JFrameMenu.JMenuVacunas.setVisible(false);
                        JFrameMenu.JMenuExportar.setVisible(false);
                        JFrameMenu.lbRolMenuPrincipal.setText("Personal médico");
                        lbRolMenuPrincipal.setVisible(false);
                        JFrameMenu.LbCedulaUsuarioIngresado.setText(logUsuDatos.getLogin_Usuario_cedula()+"");
                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(null, "Su usuario está bloqueado","Inicio de sesión",JOptionPane.WARNING_MESSAGE);
                        txtClaveLogin.setText("");
                        txtUsuarioLogin.setText("");
                        txtUsuarioLogin.requestFocus();
                    }
                    
                }
            }else{
                JOptionPane.showMessageDialog(null, "Datos incorrectos","Inicio de sesión",JOptionPane.ERROR_MESSAGE);
                txtClaveLogin.setText("");
                txtUsuarioLogin.setText("");
                txtUsuarioLogin.requestFocus();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Por favor llene todos los campos","Inicio de sesión",JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsuarioLogin = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtClaveLogin = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar sesión");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo_512x512.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, 120));

        txtUsuarioLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtUsuarioLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txtUsuarioLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 278, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        jButton1.setText("Limpiar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 110, 30));

        txtClaveLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtClaveLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtClaveLoginKeyPressed(evt);
            }
        });
        jPanel1.add(txtClaveLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 280, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Contraseña");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/marca-de-verificacion.png"))); // NOI18N
        jButton2.setText("Ingresar");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 110, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, 350));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vacunas_170x74.jpg.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Titulo_Login.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 400, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        validarInicioSesion();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtClaveLogin.setText("");
        txtUsuarioLogin.setText("");
        txtUsuarioLogin.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtClaveLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveLoginKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           validarInicioSesion();
       }
    }//GEN-LAST:event_txtClaveLoginKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtClaveLogin;
    private javax.swing.JTextField txtUsuarioLogin;
    // End of variables declaration//GEN-END:variables
}
