/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import static frame.JFrameMenu.lbRolMenuPrincipal;
import java.awt.event.KeyEvent;
import java.text.ParseException;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.DatosPacientes;
import modelo.ProcesosPacientes;

/**
 *
 * @author Holis
 */
public class JInternalRegistrarPacientes extends javax.swing.JInternalFrame {

    ProcesosPacientes pp = new ProcesosPacientes();
    DatosPacientes dp = new DatosPacientes();

    public JInternalRegistrarPacientes() {
        initComponents();
        btnActualizarRegistrarPacientes.setEnabled(false);
        if ("Personal médico".equals(lbRolMenuPrincipal.getText())) {
            btnActualizarRegistrarPacientes.setVisible(false);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCedulaRegistrarPaciente = new javax.swing.JTextField();
        txtNombreRegistrarPaciente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbEstadoCovidlRegistrarPaciente = new javax.swing.JComboBox<>();
        txtTelefonoRegistrarPaciente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCiudadRegistrarPaciente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMunicipioRegistrarPaciente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtBarrioRegistrarPaciente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnLimpiarCamposRegistrarPacientes = new javax.swing.JButton();
        btnRegistrarPacientes = new javax.swing.JButton();
        cbGeneroRegistrarPaciente1 = new javax.swing.JComboBox<>();
        cbEstadoCivilRegistrarPaciente1 = new javax.swing.JComboBox<>();
        JDateFechaNacimientoPaciente = new com.toedter.calendar.JDateChooser();
        btnActualizarRegistrarPacientes = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Registrar paciente");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cédula");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        txtCedulaRegistrarPaciente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCedulaRegistrarPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCedulaRegistrarPacienteKeyPressed(evt);
            }
        });
        jPanel1.add(txtCedulaRegistrarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 200, 30));

        txtNombreRegistrarPaciente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtNombreRegistrarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 200, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombres");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Fecha de nacimiento");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Género");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, -1, -1));

        cbEstadoCovidlRegistrarPaciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbEstadoCovidlRegistrarPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negativo", "Positivo" }));
        cbEstadoCovidlRegistrarPaciente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbEstadoCovidlRegistrarPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(cbEstadoCovidlRegistrarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 200, 30));

        txtTelefonoRegistrarPaciente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtTelefonoRegistrarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 200, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Teléfono");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Estado civil");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        txtCiudadRegistrarPaciente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtCiudadRegistrarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 200, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Ciudad");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, -1));

        txtMunicipioRegistrarPaciente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtMunicipioRegistrarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, 200, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Municipio");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, -1, -1));

        txtBarrioRegistrarPaciente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtBarrioRegistrarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 200, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Barrio");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Estado de covid");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        btnLimpiarCamposRegistrarPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpieza-de-datos.png"))); // NOI18N
        btnLimpiarCamposRegistrarPacientes.setText("Limpiar");
        btnLimpiarCamposRegistrarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposRegistrarPacientesActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiarCamposRegistrarPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 230, 100, 30));

        btnRegistrarPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/marca-de-verificacion.png"))); // NOI18N
        btnRegistrarPacientes.setText("Registrar");
        btnRegistrarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPacientesActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 110, 30));

        cbGeneroRegistrarPaciente1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbGeneroRegistrarPaciente1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenina" }));
        cbGeneroRegistrarPaciente1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbGeneroRegistrarPaciente1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(cbGeneroRegistrarPaciente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, 200, 30));

        cbEstadoCivilRegistrarPaciente1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbEstadoCivilRegistrarPaciente1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casado/a", "Soltero/a", "Viudo/a" }));
        cbEstadoCivilRegistrarPaciente1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbEstadoCivilRegistrarPaciente1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(cbEstadoCivilRegistrarPaciente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 200, 30));

        JDateFechaNacimientoPaciente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(JDateFechaNacimientoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 180, 30));

        btnActualizarRegistrarPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btnActualizarRegistrarPacientes.setText("Actualizar");
        btnActualizarRegistrarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarRegistrarPacientesActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizarRegistrarPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1104, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void registrar() {
        if ("".equals(txtCedulaRegistrarPaciente.getText()) || "".equals(txtNombreRegistrarPaciente.getText())
                || "".equals(txtTelefonoRegistrarPaciente.getText()) || "".equals(txtCiudadRegistrarPaciente.getText())
                || "".equals(txtMunicipioRegistrarPaciente.getText()) || "".equals(txtBarrioRegistrarPaciente.getText())) {
            JOptionPane.showMessageDialog(null, "Por favor llene todos los campos", "Registrar paciente", JOptionPane.ERROR_MESSAGE);

        } else {
            dp.setPcCedula(Integer.parseInt(txtCedulaRegistrarPaciente.getText().trim()));
            dp.setPcnombre(txtNombreRegistrarPaciente.getText().trim());
            dp.setPcTelefono(txtTelefonoRegistrarPaciente.getText());
            SimpleDateFormat dFormato = new SimpleDateFormat("yyyy-MM-dd");
            String fecha = dFormato.format(JDateFechaNacimientoPaciente.getDate());
            dp.setPcFechaNacimiento(fecha);
            dp.setPcGenero(cbGeneroRegistrarPaciente1.getSelectedItem().toString());
            dp.setPcEstadoCivil(cbEstadoCivilRegistrarPaciente1.getSelectedItem().toString());
            dp.setPcCiudad(txtCiudadRegistrarPaciente.getText().trim());
            dp.setPcMunicipio(txtMunicipioRegistrarPaciente.getText().trim());
            dp.setPcBarrio(txtBarrioRegistrarPaciente.getText().trim());
            dp.setPcEstadoCovid(cbEstadoCovidlRegistrarPaciente.getSelectedItem().toString());
            dp.setCedulaUsuPaciente(Integer.parseInt(JFrameMenu.LbCedulaUsuarioIngresado.getText()));
            pp.RegistrarPacientes(dp);
            JOptionPane.showMessageDialog(null, "Paciente registrado exitosamente", "Registrar paciente", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampo();

        }
    }

    private void actualizarDatosPaciente() {
        if ("".equals(txtCedulaRegistrarPaciente.getText()) || "".equals(txtNombreRegistrarPaciente.getText())
                || "".equals(txtTelefonoRegistrarPaciente.getText()) || "".equals(cbGeneroRegistrarPaciente1.getSelectedItem()) || "".equals(cbEstadoCivilRegistrarPaciente1.getSelectedItem())
                || "".equals(txtCiudadRegistrarPaciente.getText()) || "".equals(txtMunicipioRegistrarPaciente.getText()) || "".equals(txtBarrioRegistrarPaciente.getText())
                || "".equals(cbEstadoCovidlRegistrarPaciente.getSelectedItem())) {
            JOptionPane.showMessageDialog(null, "Por favor llene todos los campos", "Registrar paciente", JOptionPane.ERROR_MESSAGE);

        } else {
            dp.setPcnombre(txtNombreRegistrarPaciente.getText().trim());
            dp.setPcTelefono(txtTelefonoRegistrarPaciente.getText());
            
            SimpleDateFormat dFormato = new SimpleDateFormat("yyyy-MM-dd");
            String fecha = dFormato.format(JDateFechaNacimientoPaciente.getDate());
            dp.setPcFechaNacimiento(fecha);
            
            dp.setPcGenero(cbGeneroRegistrarPaciente1.getSelectedItem().toString());
            dp.setPcEstadoCivil(cbEstadoCivilRegistrarPaciente1.getSelectedItem().toString());
            dp.setPcCiudad(txtCiudadRegistrarPaciente.getText().trim());
            dp.setPcMunicipio(txtMunicipioRegistrarPaciente.getText().trim());
            dp.setPcBarrio(txtBarrioRegistrarPaciente.getText().trim());
            dp.setPcEstadoCovid(cbEstadoCovidlRegistrarPaciente.getSelectedItem().toString());
            dp.setPcCedula(Integer.parseInt(txtCedulaRegistrarPaciente.getText().trim()));
            pp.ActualizarDatosPacientes(dp);
            JOptionPane.showMessageDialog(null, "Datos actualizados exitosamente", "Actualizar datos del paciente", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampo();

        }

    }

    private void buscarPaciente() {
        if (!"".equals(txtCedulaRegistrarPaciente.getText())) {
            int cedula = Integer.parseInt(txtCedulaRegistrarPaciente.getText());
            dp = pp.BuscarDatos(cedula);
            if (dp.getPcnombre() != null) {
                txtNombreRegistrarPaciente.setText(dp.getPcnombre());
                txtTelefonoRegistrarPaciente.setText(dp.getPcTelefono());
                SimpleDateFormat dFormato = new SimpleDateFormat("yyyy-MM-dd");
                Date fecha;

                try {
                    fecha = dFormato.parse(dp.getPcFechaNacimiento());
                    JDateFechaNacimientoPaciente.setDate(fecha);
                } catch (ParseException e) {
                    System.out.println(e.toString());
                }
                cbGeneroRegistrarPaciente1.setSelectedItem(dp.getPcGenero());
                cbEstadoCivilRegistrarPaciente1.setSelectedItem(dp.getPcEstadoCivil());
                txtCiudadRegistrarPaciente.setText(dp.getPcCiudad());
                txtMunicipioRegistrarPaciente.setText(dp.getPcMunicipio());
                txtBarrioRegistrarPaciente.setText(dp.getPcBarrio());
                cbEstadoCovidlRegistrarPaciente.setSelectedItem(dp.getPcEstadoCovid());
                btnRegistrarPacientes.setEnabled(false);
                btnActualizarRegistrarPacientes.setEnabled(true);
                txtCedulaRegistrarPaciente.setEnabled(false);

            } else {
                JOptionPane.showMessageDialog(null, "El paciente no existe", "Buscar paciente", JOptionPane.ERROR_MESSAGE);
                limpiarCampo();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor digite la cédula", "Buscar paciente", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpiarCampo() {
        txtCedulaRegistrarPaciente.setText("");
        txtNombreRegistrarPaciente.setText("");
        txtTelefonoRegistrarPaciente.setText("");
        txtBarrioRegistrarPaciente.setText("");
        txtCiudadRegistrarPaciente.setText("");
        txtMunicipioRegistrarPaciente.setText("");
        txtCedulaRegistrarPaciente.requestFocus();
        btnActualizarRegistrarPacientes.setEnabled(false);
        btnRegistrarPacientes.setEnabled(true);
        txtCedulaRegistrarPaciente.setEnabled(true);

    }

    private void btnRegistrarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPacientesActionPerformed
        registrar();

    }//GEN-LAST:event_btnRegistrarPacientesActionPerformed

    private void btnActualizarRegistrarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarRegistrarPacientesActionPerformed
        actualizarDatosPaciente();

    }//GEN-LAST:event_btnActualizarRegistrarPacientesActionPerformed

    private void btnLimpiarCamposRegistrarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposRegistrarPacientesActionPerformed
        limpiarCampo();
    }//GEN-LAST:event_btnLimpiarCamposRegistrarPacientesActionPerformed

    private void txtCedulaRegistrarPacienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaRegistrarPacienteKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buscarPaciente();
        }
    }//GEN-LAST:event_txtCedulaRegistrarPacienteKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDateFechaNacimientoPaciente;
    public static javax.swing.JButton btnActualizarRegistrarPacientes;
    private javax.swing.JButton btnLimpiarCamposRegistrarPacientes;
    private javax.swing.JButton btnRegistrarPacientes;
    private javax.swing.JComboBox<String> cbEstadoCivilRegistrarPaciente1;
    private javax.swing.JComboBox<String> cbEstadoCovidlRegistrarPaciente;
    private javax.swing.JComboBox<String> cbGeneroRegistrarPaciente1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtBarrioRegistrarPaciente;
    private javax.swing.JTextField txtCedulaRegistrarPaciente;
    private javax.swing.JTextField txtCiudadRegistrarPaciente;
    private javax.swing.JTextField txtMunicipioRegistrarPaciente;
    private javax.swing.JTextField txtNombreRegistrarPaciente;
    private javax.swing.JTextField txtTelefonoRegistrarPaciente;
    // End of variables declaration//GEN-END:variables
}
