/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelo.DatosVacunacion;
import modelo.ProcesosVacunacion;

/**
 *
 * @author Asus
 */
public class JInternalBuscarPacienteVacunacion extends javax.swing.JInternalFrame {

    DatosVacunacion dv = new DatosVacunacion();
    ProcesosVacunacion pv = new ProcesosVacunacion();
    DefaultTableModel modelo = new DefaultTableModel();
    
    TableRowSorter trs;

    public JInternalBuscarPacienteVacunacion() {
        initComponents();
        limpiarTabla();
        listarPacientesVacunados();
    }

    private void limpiarTabla() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i--;
        }
    }

    private void listarPacientesVacunados() {
        List<DatosVacunacion> listVa = pv.listar();
        modelo = (DefaultTableModel) tbMostrarFiltroPaciente.getModel();
        Object[] ob = new Object[8];
        for (int i = 0; i < listVa.size(); i++) {
            ob[0] = listVa.get(i).getPvc_cedula_paciente();
            ob[1] = listVa.get(i).getPvc_nombres_paciente();
            ob[2] = listVa.get(i).getPvc_codigo_vacuna();
            ob[3] = listVa.get(i).getPvc_nombre_vacuna();
            ob[4] = listVa.get(i).getPvc_laboratorio_vacuna();
            ob[5] = listVa.get(i).getPvc_dosis();
            ob[6] = listVa.get(i).getPvc_fecha_registro();
            ob[7] = listVa.get(i).getPvc_cedula_usuario();
            modelo.addRow(ob);
        }
        tbMostrarFiltroPaciente.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCedulaBusquedaPaciente = new javax.swing.JTextField();
        btnBuscarPacienteBusqueda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMostrarFiltroPaciente = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Buscar el proceso de vacunación de un paciente");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cedula del paciente");

        txtCedulaBusquedaPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaBusquedaPacienteKeyTyped(evt);
            }
        });

        btnBuscarPacienteBusqueda.setText("Buscar");
        btnBuscarPacienteBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPacienteBusquedaActionPerformed(evt);
            }
        });

        tbMostrarFiltroPaciente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbMostrarFiltroPaciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbMostrarFiltroPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Nombre", "Codigo vacuna", "Nombre vacuna", "Laboratorio", "Dosis", "Fecha vacunacion", "Cedula medico"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbMostrarFiltroPaciente);
        if (tbMostrarFiltroPaciente.getColumnModel().getColumnCount() > 0) {
            tbMostrarFiltroPaciente.getColumnModel().getColumn(0).setPreferredWidth(25);
            tbMostrarFiltroPaciente.getColumnModel().getColumn(2).setPreferredWidth(30);
            tbMostrarFiltroPaciente.getColumnModel().getColumn(5).setPreferredWidth(10);
            tbMostrarFiltroPaciente.getColumnModel().getColumn(7).setPreferredWidth(10);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCedulaBusquedaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnBuscarPacienteBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedulaBusquedaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPacienteBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarPacienteBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPacienteBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarPacienteBusquedaActionPerformed

    private void txtCedulaBusquedaPacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaBusquedaPacienteKeyTyped
        
        txtCedulaBusquedaPaciente.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent ke) {
                trs.setRowFilter(RowFilter.regexFilter(txtCedulaBusquedaPaciente.getText(), 0));
            }

        });
        
        trs = new TableRowSorter(modelo);
        tbMostrarFiltroPaciente.setRowSorter(trs);
    }//GEN-LAST:event_txtCedulaBusquedaPacienteKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPacienteBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbMostrarFiltroPaciente;
    private javax.swing.JTextField txtCedulaBusquedaPaciente;
    // End of variables declaration//GEN-END:variables
}
