/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import modelo.DatosGraficas;
import modelo.ProcesosGraficas;
import modelo.TodosLosSintomas;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Holis
 */
public class JInternalGraficaSintomasComunes extends javax.swing.JInternalFrame {

    DatosGraficas dg = new DatosGraficas();
    ProcesosGraficas pg = new ProcesosGraficas();

    public JInternalGraficaSintomasComunes() {
        initComponents();
    }

    private void buscarSintomas() {

        dg = pg.buscarSintomas(cbSintomas.getSelectedItem().toString());
        int sintoma = dg.getCantidadSintomasReportados();

        //sacar de la base de datos tu los borras.
        DefaultCategoryDataset datos = new DefaultCategoryDataset();//Establecer los valores(supongo que tambien lo quitas)

        datos.setValue(sintoma, "Cantidad", cbSintomas.getSelectedItem().toString());//Los datos almacenados
        //datos.setValue(f2, "Cantidad", fecha2);

        JFreeChart grafico_barras = ChartFactory.createBarChart3D(
                "Cantidad de personas con este sintoma", //NOMBRE DEL GRAFICO
                "Sintoma", //NOMBRE DE LAS BARRAS O COLUMNAS
                "Cantidad", //NOMBRE DE NUMERACION
                datos, //datos de barras
                PlotOrientation.VERTICAL, //ORIENTACION
                true, //barra individual por colores
                true, //herramientas
                false //url del grafico
        );

        ChartPanel panel = new ChartPanel(grafico_barras);  //Creando un panel tipo chart
        panel.setMouseWheelEnabled(true);                   //Mouse Habilitado (Ruenda del raton para manipular)
        panel.setPreferredSize(new Dimension(732, 437));     //Dimension

        JPanelGraficoSintomasComunes.setLayout(new BorderLayout());         //Asignando al panel donde va el grafico con bordes
        JPanelGraficoSintomasComunes.add(panel, BorderLayout.NORTH);
        JPanelGraficoSintomasComunes.setEnabled(false);
        pack();//Estos son necesarios para el grafico
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JPanelGraficoSintomasComunes = new javax.swing.JPanel();
        cbSintomas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Sintomas más comunes");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        JPanelGraficoSintomasComunes.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout JPanelGraficoSintomasComunesLayout = new javax.swing.GroupLayout(JPanelGraficoSintomasComunes);
        JPanelGraficoSintomasComunes.setLayout(JPanelGraficoSintomasComunesLayout);
        JPanelGraficoSintomasComunesLayout.setHorizontalGroup(
            JPanelGraficoSintomasComunesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
        );
        JPanelGraficoSintomasComunesLayout.setVerticalGroup(
            JPanelGraficoSintomasComunesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );

        cbSintomas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbSintomas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fiebre", "Vomito", "Diarrea", "Dolor de barriga" }));
        cbSintomas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbSintomas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSintomasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Selecciones el sintoma");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Ver todos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbSintomas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(JPanelGraficoSintomasComunes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbSintomas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(JPanelGraficoSintomasComunes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbSintomasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSintomasActionPerformed
        dg = pg.buscarSintomas(cbSintomas.getSelectedItem().toString());
        int sintoma = dg.getCantidadSintomasReportados();
        System.out.println(sintoma);
        if (sintoma != 0) {
            JPanelGraficoSintomasComunes.removeAll();
            JPanelGraficoSintomasComunes.revalidate();
            JPanelGraficoSintomasComunes.repaint();
            buscarSintomas();
        } else {
            JPanelGraficoSintomasComunes.removeAll();
            JPanelGraficoSintomasComunes.revalidate();
            JPanelGraficoSintomasComunes.repaint();
            JOptionPane.showMessageDialog(null, "No hay paciente con este sintoma", "Buscar sintomas", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_cbSintomasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       TodosLosSintomas todos = new TodosLosSintomas();
       todos.todosLosSintomas();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelGraficoSintomasComunes;
    private javax.swing.JComboBox<String> cbSintomas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
