/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelo.DatosUsuarios;
import modelo.ProcesoLoginUsuario;

/**
 *
 * @author Holis
 */
public class JInternalBloquearUsuario extends javax.swing.JInternalFrame {

    DatosUsuarios ds = new DatosUsuarios();
    ProcesoLoginUsuario plu = new ProcesoLoginUsuario();
    public JInternalBloquearUsuario() {
        initComponents();
    }
    public void limpiarCampos(){
        txtCedulaUsuarioBloqueo.setText("");
        txtNombreUsuarioBloqueo.setText("");
        txtCedulaUsuarioBloqueo.requestFocus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCedulaUsuarioBloqueo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNombreUsuarioBloqueo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBloquearUsuario = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Bloquear usuario");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCedulaUsuarioBloqueo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCedulaUsuarioBloqueo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCedulaUsuarioBloqueoKeyPressed(evt);
            }
        });
        jPanel1.add(txtCedulaUsuarioBloqueo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 180, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Ingrese la cédula");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 180, -1));

        txtNombreUsuarioBloqueo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNombreUsuarioBloqueo.setEnabled(false);
        jPanel1.add(txtNombreUsuarioBloqueo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 180, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombre del usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 180, -1));

        btnBloquearUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bloquear.png"))); // NOI18N
        btnBloquearUsuario.setText("Bloquear");
        btnBloquearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBloquearUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnBloquearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBloquearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBloquearUsuarioActionPerformed
        if("".equals(txtCedulaUsuarioBloqueo.getText())|| "".equals(txtNombreUsuarioBloqueo.getText())){
            JOptionPane.showMessageDialog(null, "Hay campos vacíos","Bloquear usuario",JOptionPane.WARNING_MESSAGE);
        }else{
            ds=plu.buscarUsuario(Integer.parseInt(txtCedulaUsuarioBloqueo.getText()));
            System.out.println(ds.getLogin_Usuario_estado_cuenta());
            if("Inactivo".equals(ds.getLogin_Usuario_estado_cuenta())){
                int res=JOptionPane.showConfirmDialog(null, "Este usuario esta bloqueado, ¿Desea desbloquearlo?", "Bloquear usuario",JOptionPane.WARNING_MESSAGE);
                if(res==0){
                    ds.setLogin_Usuario_estado_cuenta("Activo");
                    ds.setLogin_Usuario_cedula(Integer.parseInt(txtCedulaUsuarioBloqueo.getText()));
                    plu.bloquearUsuario(ds);
                    JOptionPane.showMessageDialog(null, "Usuario desbloqueado","Bloquear usuario",JOptionPane.INFORMATION_MESSAGE);
                    limpiarCampos();
                }else{
                    JOptionPane.showMessageDialog(null, "Usuario no bloqueado","Bloquear usuario",JOptionPane.INFORMATION_MESSAGE);
                }
            }else{
                ds.setLogin_Usuario_estado_cuenta("Inactivo");
                ds.setLogin_Usuario_cedula(Integer.parseInt(txtCedulaUsuarioBloqueo.getText()));
                plu.bloquearUsuario(ds);
                JOptionPane.showMessageDialog(null, "Usuario bloqueado","Bloquear usuario",JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos();
            }
        }
    }//GEN-LAST:event_btnBloquearUsuarioActionPerformed

    private void txtCedulaUsuarioBloqueoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaUsuarioBloqueoKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            ds=plu.buscarUsuario(Integer.parseInt(txtCedulaUsuarioBloqueo.getText()));
            txtNombreUsuarioBloqueo.setText(ds.getLogin_Usuario_nombre());
        }
    }//GEN-LAST:event_txtCedulaUsuarioBloqueoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBloquearUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCedulaUsuarioBloqueo;
    private javax.swing.JTextField txtNombreUsuarioBloqueo;
    // End of variables declaration//GEN-END:variables
}
